# Generated by Django 4.2.1 on 2023-06-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='user_profile/usrDefaultImage.png', upload_to='user_profile/'),
        ),
    ]
