# Generated by Django 4.2.1 on 2023-06-26 16:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='user_profile/usrDefaultImage.png', upload_to=accounts.models.get_file_path_user),
        ),
    ]
