# Generated by Django 4.2.2 on 2023-06-28 04:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dgupass',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_file_path_user),
        ),
        migrations.AddField(
            model_name='profile',
            name='dgupass_approved',
            field=models.BooleanField(default=False),
        ),
    ]
