# Generated by Django 4.2.2 on 2023-06-28 04:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_dgupass_profile_dgupass_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dgupass',
            field=models.ImageField(default=False, upload_to=accounts.models.get_file_path_user),
        ),
    ]
