# Generated by Django 4.2.1 on 2023-06-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='filename',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
