# Generated by Django 4.2.1 on 2023-06-24 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_somd_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='somd',
            name='join_members',
            field=models.ManyToManyField(blank=True, related_name='join_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='somd',
            name='waitTojoin_members',
            field=models.ManyToManyField(blank=True, related_name='waitTojoin_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
