# Generated by Django 4.2.1 on 2023-06-23 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_somd_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='somd',
            name='join_members',
            field=models.ManyToManyField(blank=True, related_name='join_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
