# Generated by Django 4.2.1 on 2023-06-24 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_somd_join_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinrequest',
            old_name='created_at',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='member',
            name='rejected_somds',
            field=models.ManyToManyField(blank=True, related_name='rejected_somds', to='main.somd'),
        ),
        migrations.AddField(
            model_name='member',
            name='waiting_somds',
            field=models.ManyToManyField(blank=True, related_name='waiting_somds', to='main.somd'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
