# Generated by Django 4.2.1 on 2023-06-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_created_at_joinrequest_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_comments',
        ),
    ]
