# Generated by Django 4.2.1 on 2023-06-25 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_somd_admins_remove_somd_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
    ]
