# Generated by Django 4.2.1 on 2023-06-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_post_is_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_pinned',
            new_name='is_fix',
        ),
    ]
