# Generated by Django 4.2.1 on 2023-06-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_is_pinned_post_is_fix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_fix',
            new_name='is_fixed',
        ),
    ]
