# Generated by Django 4.2.1 on 2023-06-25 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_is_fix_post_is_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='somd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.somd'),
        ),
    ]
