# Generated by Django 4.2.1 on 2023-06-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_alter_post_somd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('post', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('sendUser', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('somd', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.somd')),
            ],
        ),
        migrations.CreateModel(
            name='UserAlram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somds', models.ManyToManyField(blank=True, related_name='alram', to='main.alram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
