# Generated by Django 4.2.1 on 2023-06-25 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0025_alter_alram_post_alter_alram_senduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
