# Generated by Django 4.2.1 on 2023-06-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_alram_post_alter_alram_senduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alram',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
