# Generated by Django 4.2.2 on 2023-06-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_post_comment_count_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
