# Generated by Django 4.2.2 on 2023-06-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_somd_backgroundimage_alter_somd_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_fixed_count',
            field=models.IntegerField(default=0),
        ),
    ]
