# Generated by Django 4.2.2 on 2023-06-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_post_is_fixed_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_fixed_count',
        ),
    ]
