# Generated by Django 4.2.1 on 2023-06-21 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_somd_bookmark_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
