# Generated by Django 4.2.1 on 2023-06-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='Images',
        ),
    ]
