# Generated by Django 4.2.1 on 2023-06-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_images_post_alter_post_somd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='somd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='somds', to='main.somd'),
        ),
    ]
