# Generated by Django 4.2.1 on 2023-06-24 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_remove_joinrequest_user_somd_join_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
