# Generated by Django 4.2.1 on 2023-06-25 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_alter_useralram_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alram',
            name='sendUser',
        ),
        migrations.AddField(
            model_name='alram',
            name='sendUser',
            field=models.ManyToManyField(blank=True, null=True, related_name='sendUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
