# Generated by Django 4.2.1 on 2023-06-26 16:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_somd_filename_back_somd_filename_prof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somd',
            name='backgroundimage',
            field=models.ImageField(blank=True, default='somd/somdbackDefaultImage.png', null=True, upload_to=main.models.get_file_path_somd),
        ),
        migrations.AlterField(
            model_name='somd',
            name='profileimage',
            field=models.ImageField(blank=True, default='somd/somdDefaultImage.png', null=True, upload_to=main.models.get_file_path_somd),
        ),
    ]
